# Hand-built gender dictionary for nouns not otherwise determinable from the
# rest of the corpus. Built from German compound-noun rule (gender = gender
# of the LAST component, e.g. "Bauplan" -> "Plan" -> masc) and standard
# suffix patterns (-ung/-heit/-keit/-schaft/-tät/-ie/-ik/-ion/-anz -> fem;
# -chen/-lein/-um -> neut; -er agent nouns -> masc), supplemented by direct
# vocabulary knowledge for simplex/loan words. For inherently-plural entries
# the guessed gender barely matters (the pipeline always tries the plural
# reading too and accepts whichever matches the real observed article), so
# these are best-effort rather than carefully researched.
# NOT included: "gewusst" (a past participle -- "das gewusst hättest" is
# actually "das" as a demonstrative pronoun object of wissen, not an
# article+noun at all; a genuine data anomaly, deliberately left unconverted).
# "Ummelden" IS included below, unlike a plain verb infinitive would be --
# "das Ummelden" is a real nominalized-infinitive noun ("the re-registering"),
# and nominalized infinitives in German are always neuter, a fully regular rule.

KNOWN_GENDERS = {
    "Abfindung": "Fem", "Abflug": "Masc", "Abfluss": "Masc", "Abnahme": "Fem",
    "Abo": "Neut", "Abonnenten": "Masc", "Abschlussfeier": "Fem", "Aktenordner": "Masc",
    "Aktien": "Fem", "Alarmanlage": "Fem", "Album": "Neut", "Alleinstellungsmerkmal": "Neut",
    "Anfahrt": "Fem", "Anschlusszug": "Masc", "Anwohner": "Masc", "Anzahlung": "Fem",
    "Architekten": "Masc", "Auffahrt": "Fem", "Aufgabenliste": "Fem", "Bademantel": "Masc",
    "Badematte": "Fem", "Bagger": "Masc", "Ballett": "Neut", "Band": "Neut",
    "Bandbreite": "Fem", "Baufinanzierung": "Fem", "Baugenehmigung": "Fem",
    "Baumaschine": "Fem", "Bauplan": "Masc", "Bauzaun": "Masc", "Beeren": "Fem",
    "Berghütte": "Fem", "Beruf": "Masc", "Besucher": "Masc", "Bewegungsmelder": "Masc",
    "Bewertung": "Fem", "Bewässerung": "Fem", "Bienenstock": "Masc", "Bilanz": "Fem",
    "Blumenbeete": "Neut", "Blumenschmuck": "Masc", "Blut": "Neut", "Boiler": "Masc",
    "Boulderhalle": "Fem", "Bowlingkugel": "Fem", "Brautjungfer": "Fem", "Brennholz": "Neut",
    "Brettspiel": "Neut", "Brotdose": "Fem", "Browser": "Masc", "Buchführung": "Fem",
    "Buchhaltung": "Fem", "Businessplan": "Masc", "Bücherschrank": "Masc",
    "Bürgschaft": "Fem", "Cache": "Masc", "Cloud": "Fem", "Coupons": "Masc",
    "DJ": "Masc", "Danksagungskarten": "Fem", "Darlehen": "Neut", "Dauerauftrag": "Masc",
    "Deadline": "Fem", "Depot": "Neut", "Deutsch": "Neut", "Dienst": "Masc",
    "Dienstplan": "Masc", "Dämmung": "Fem", "Ehering": "Masc", "Einladungskarten": "Fem",
    "Einstellungen": "Fem", "Eislaufplatz": "Masc", "Elektrik": "Fem",
    "Energieausweis": "Masc", "Erbschaft": "Fem", "Erinnerung": "Fem",
    "Erste-Hilfe-Kasten": "Masc", "Estrich": "Masc", "Fahrgemeinschaft": "Fem",
    "Fahrkartenautomaten": "Masc", "Fahrradkette": "Fem", "Fahrschule": "Fem",
    "Fassade": "Fem", "Feuerlöscher": "Masc", "Fieber": "Neut", "Filter": "Masc",
    "Firewall": "Fem", "Fische": "Masc", "Fliesen": "Fem", "Flitterwochen": "Fem",
    "Flitterwochenfotos": "Neut", "Fluchtplan": "Masc", "Fonds": "Masc",
    "Fotografen": "Masc", "Fremdwährung": "Fem", "Fundament": "Neut", "Führung": "Fem",
    "Garantie": "Fem", "Gardinen": "Fem", "Gartenschuppen": "Masc", "Gasanbieter": "Masc",
    "Geburtsurkunde": "Fem", "Gebühr": "Fem", "Gefrierschrank": "Masc",
    "Gehaltsabrechnung": "Fem", "Gehaltsverhandlung": "Fem", "Gerüst": "Neut",
    "Geschenkliste": "Fem", "Geschwister": "Neut", "Getränkeauswahl": "Fem",
    "Gewerbe": "Neut", "Gewinnausschüttung": "Fem", "Gewährleistung": "Fem",
    "Gleis": "Neut", "Gläubiger": "Masc", "Golfschläger": "Masc", "Grundriss": "Masc",
    "Gutachten": "Neut", "Gutschein": "Masc", "Gästeliste": "Fem", "Gästezimmer": "Neut",
    "Gürtel": "Masc", "Haftpflichtversicherung": "Fem", "Handschuhe": "Masc",
    "Handwerker": "Masc", "Haushaltsplan": "Masc", "Hausnummer": "Fem",
    "Hausratversicherung": "Fem", "Heimreise": "Fem", "Heiratsurkunde": "Fem",
    "Heizkosten": "Fem", "Heizkörper": "Masc", "Herausforderung": "Fem",
    "Hochbeet": "Neut", "Hochzeitskleid": "Neut", "Hundeführerschein": "Masc",
    "Hypothek": "Fem", "Hörtest": "Masc", "Igel": "Masc", "Insolvenzantrag": "Masc",
    "Investoren": "Masc", "Jahresabschluss": "Masc", "Jetlag": "Masc",
    "Jobticket": "Neut", "Kalorien": "Fem", "Kantine": "Fem", "Karneval": "Masc",
    "Karpfenteich": "Masc", "Kaufpreis": "Masc", "Kaufvertrag": "Masc", "Kette": "Fem",
    "Kleiderschrank": "Masc", "Kletterausrüstung": "Fem", "Klettergurtzeug": "Neut",
    "Klimaanlage": "Fem", "Klingel": "Fem", "Klingelschild": "Neut", "Knöllchen": "Neut",
    "Kompost": "Masc", "Komposter": "Masc", "Komposthaufen": "Masc",
    "Konzertticket": "Neut",
    "Kontaktlinsen": "Fem", "Kostenvoranschlag": "Masc", "Kran": "Masc",
    "Kräuter": "Neut", "Kundenzufriedenheit": "Fem", "Lage": "Fem",
    "Lagerbestand": "Masc", "Lagerfeuer": "Neut", "Laufschuhe": "Masc",
    "Lenker": "Masc", "Liege": "Fem", "Linse": "Fem", "Logo": "Neut", "Loipe": "Fem",
    "Markise": "Fem", "Marktanalyse": "Fem", "Marmelade": "Fem", "Marshmallows": "Masc",
    "Maut": "Fem", "Mieterhöhung": "Fem", "Mietpreis": "Masc",
    "Mitarbeitergespräch": "Neut", "Motorradhelm": "Masc", "Muscheln": "Fem",
    "Mängel": "Masc", "Nachfrage": "Fem", "Nachlass": "Masc", "Nachnamen": "Masc",
    "Nachsendeantrag": "Masc", "Nachteil": "Masc", "Namensschild": "Neut",
    "Nebenkosten": "Fem", "Newsletter": "Masc", "Nische": "Fem", "Notartermin": "Masc",
    "Notausgänge": "Masc", "Notfallreserve": "Fem", "Obstbaum": "Masc", "Oper": "Fem",
    "Osterei": "Neut", "PIN": "Fem", "Paketschein": "Masc", "Papier": "Neut",
    "Parkgebühr": "Fem", "Physiotherapie": "Fem", "Pilze": "Masc", "Playlist": "Fem",
    "Police": "Fem", "Preiserhöhung": "Fem", "Preisschilder": "Neut",
    "Preisstrategie": "Fem", "Profil": "Neut", "Pumpe": "Fem", "Rasensprenger": "Masc",
    "Rate": "Fem", "Ratenzahlung": "Fem", "Rauchmelder": "Masc", "Regenrinne": "Fem",
    "Regentonne": "Fem", "Regenwasser": "Neut", "Reichweite": "Fem",
    "Reifendruck": "Masc", "Reinigungsfirma": "Fem", "Reiseblog": "Masc",
    "Reisenden": "Fem", "Reisepass": "Masc", "Reiseversicherung": "Fem",
    "Reklamation": "Fem", "Reste": "Masc", "Retourenlabel": "Neut", "Rodelhang": "Masc",
    "Rohbau": "Masc", "Rohre": "Neut", "Rollladen": "Masc", "Rückflug": "Masc",
    "Rücksendung": "Fem", "Samen": "Masc", "Sandburg": "Fem", "Sattel": "Masc",
    "Sauerteig": "Masc", "Schadensfall": "Masc", "Schicht": "Fem",
    "Schlittschuhe": "Masc", "Schlussrechnung": "Fem", "Schlüsseldienst": "Masc",
    "Schneeketten": "Fem", "Schufa-Auskunft": "Fem", "Schutt": "Masc",
    "Schutzbrille": "Fem", "Schwimmweste": "Fem", "Sicherheitsschulung": "Fem",
    "Siegel": "Neut", "Silvesterparty": "Fem", "Sinn": "Masc", "Sitzordnung": "Fem",
    "Ski": "Masc", "Skier": "Masc", "Snooze-Taste": "Fem", "Solarzellen": "Fem",
    "Sonnenkollektoren": "Masc", "Sonnenschirm": "Masc", "Souvenir": "Neut",
    "Spedition": "Fem", "Speisekammer": "Fem", "Spielregeln": "Fem",
    "Sprachprüfung": "Fem", "Standesamt": "Neut", "Startup": "Neut", "Stativ": "Neut",
    "Sterne": "Masc", "Steuer": "Fem", "Steuerberater": "Masc", "Steuerklasse": "Fem",
    "Steuernummer": "Fem", "Stipendium": "Neut", "Strategie": "Fem",
    "Streaming-Abo": "Neut", "Stromanbieter": "Masc", "Stromvertrag": "Masc",
    "Studiengang": "Masc", "Studienort": "Masc", "Surfbrett": "Neut", "Tacho": "Masc",
    "Tapete": "Fem", "Tauchausrüstung": "Fem", "Terrarium": "Neut",
    "Thermostat": "Masc", "Tierarztrechnung": "Fem", "Tilgung": "Fem",
    "Tischdekoration": "Fem", "Tonerpatrone": "Fem", "Touristen": "Masc",
    "Trauzeugen": "Masc", "Umleitung": "Fem", "Ummelden": "Neut",
    "Ventilator": "Masc", "Verkehrsregelung": "Fem", "Versand": "Masc",
    "Versicherungsschutz": "Masc", "Virenschutz": "Masc", "Visitenkarte": "Fem",
    "Visitenkarten": "Fem", "Vogelhaus": "Neut", "Vogeltränke": "Fem", "Voliere": "Fem",
    "Vollmacht": "Fem", "Vorräte": "Masc", "Vorteil": "Masc", "Wanderschuhe": "Masc",
    "Warnweste": "Fem", "Wasserhahn": "Masc", "Wasserzähler": "Masc",
    "Wechselstube": "Fem", "Weihnachtsbaum": "Masc", "Weinflasche": "Fem",
    "Werbekampagne": "Fem", "Werkzeugkasten": "Masc", "Wettbewerb": "Masc",
    "Whirlpool": "Masc", "Windschutzscheibe": "Fem", "Wirtschaftsprüfer": "Masc",
    "Wocheneinkauf": "Masc", "Wände": "Fem", "Yogamatte": "Fem",
    "Zahnarzttermin": "Masc", "Zahnspange": "Fem", "Zelte": "Neut", "Zielgruppe": "Fem",
    "Zielvereinbarung": "Fem", "Zinssatz": "Masc", "Zoll": "Masc",
    "Zugangskarte": "Fem", "Zwei-Faktor-Authentifizierung": "Fem",
    "Zählerstand": "Masc", "Zündkerzen": "Fem", "Ärzte": "Masc", "Öffis": "Fem",
    "Ölkanne": "Fem", "Ölwechsel": "Masc", "Überwachungskamera": "Fem",
}
